# Generated by Django 5.1 on 2024-08-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_attendees",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
